version: "2"
services:
  main:
    image: ndaidong/farecogn
    volumes:
      - .:/home:z
    ports:
      - "8086:8086"
    environment:
      - APP_ENV=development
      - FLASK_DEBUG=1
    # restart: always
    entrypoint: |
      bash -c 'bash -s <<EOF
      cd /home
      pip install virtualenv
      virtualenv --system-site-packages env
      source env/bin/activate
      pip install -r requirements.txt
      export FLASK_APP=server.py
      flask run --host=0.0.0.0 --port=8086
      EOF'
